name: Deploy Repository

on:
  workflow_dispatch:

jobs:
  deploy-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup fianu
        uses: fianulabs/actions@main
        with:
          version: 1.9.36-beta-5

      - name: Run Fianu deploy command
        run: |
          fianu console deploy good/*


        env:
          FIANU_USERNAME: ${{ secrets.FIANU_USERNAME }}
          FIANU_CLIENT_ID: ${{ secrets.FIANU_CLIENT_ID }}
          FIANU_CLIENT_SECRET: ${{ secrets.FIANU_CLIENT_SECRET }}
          FIANU_HOST: ${{ secrets.FIANU_HOST }}