name: Deploy Repository

on:
  push:
    branches:
      - main

jobs:
  deploy-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Fianu
        uses: fianulabs/actions@main
        with:
          version: ${{ secrets.FIANU_VERSION }}

      - name: Run Fianu deploy command
        run: |
          fianu console deploy exceptions/*

        env:
          FIANU_USERNAME: ${{ secrets.FIANU_DEMO_USERNAME }}
          FIANU_CLIENT_ID: ${{ secrets.FIANU_DEMO_CLIENT_ID }}
          FIANU_CLIENT_SECRET: ${{ secrets.FIANU_DEMO_CLIENT_SECRET }}
          FIANU_HOST: ${{ secrets.FIANU_DEMO_HOST }}