name: Remove Policy Exception

on:
  workflow_dispatch:

jobs:
  deploy-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Fianu remove command
        run: |
          bin/fianu console remove example/dbx/exception.yaml