name: Remove Policy Exception

on:
  workflow_dispatch:

jobs:
  deploy-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup fianu
        uses: fianulabs/actions@main
        with:
          version: 1.9.36-beta-2
          
      - name: Run Fianu remove command
        run: |
          fianu console remove example/dbx/exception.yaml
        
        env:
          FIANU_USERNAME: ${{ secrets.FIANU_USERNAME }}
          FIANU_CLIENT_ID: ${{ secrets.FIANU_CLIENT_ID }}
          FIANU_CLIENT_SECRET: ${{ secrets.FIANU_CLIENT_SECRET }}
          FIANU_HOST: ${{ secrets.FIANU_HOST }}
